---
version: "3"
services:
  posterizarr:
    hostname: "posterizarr"
    container_name: "posterizarr"
    environment:
      - "PGID=1000"
      - "PUID=1000"
      - "TZ=Europe/Berlin"
      - "UMASK=022"
      - "TERM=xterm"
      - "RUN_TIME=10:30,19:30"
    image: "ghcr.io/fscorrupt/docker-posterizarr-dev:latest"
    restart: "unless-stopped"
    networks:
      - "proxy"
    volumes:
      - "/opt/appdata/posterizarr:/config:rw"
networks:
  proxy:
    driver: bridge
    external: true
