name: Build Multi Stage Docker Image
on:
  push:
  schedule:
    - cron: '0 5 * * *'
jobs:
  GHRC:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v6.4
        name: Build & push Docker image
        with:
          image: repo/image
          registry: ghcr.io
          multiPlatform: true
          platform: linux/amd64,linux/arm64,linux/arm/v7
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
